// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUJ_ca1rPSKlmsi8osepkcqNpJj9ExD7Q',
    appId: '1:1096833744362:web:7386f1829ef0d76a090693',
    messagingSenderId: '1096833744362',
    projectId: 'calculadoras-fertisystem',
    authDomain: 'calculadoras-fertisystem.firebaseapp.com',
    storageBucket: 'calculadoras-fertisystem.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5apIkkYQ4CBKnk6XaVo61VZk5Rx2KrV4',
    appId: '1:1096833744362:android:598a28a33e0f4cec090693',
    messagingSenderId: '1096833744362',
    projectId: 'calculadoras-fertisystem',
    storageBucket: 'calculadoras-fertisystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxUN5K7NWDOe675xflq0kADyUIoVeaL0',
    appId: '1:1096833744362:ios:e10f59bdbe819920090693',
    messagingSenderId: '1096833744362',
    projectId: 'calculadoras-fertisystem',
    storageBucket: 'calculadoras-fertisystem.appspot.com',
    iosBundleId: 'com.example.testeCalculadora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuxUN5K7NWDOe675xflq0kADyUIoVeaL0',
    appId: '1:1096833744362:ios:1a2fdc6ebaa621db090693',
    messagingSenderId: '1096833744362',
    projectId: 'calculadoras-fertisystem',
    storageBucket: 'calculadoras-fertisystem.appspot.com',
    iosBundleId: 'com.example.testeCalculadora.RunnerTests',
  );
}
